---
changelog:
  exclude:
    authors:
      - dependabot[bot]
      - pre-commit-ci[bot]
  categories:
    - title: PRs with deployment notes
      labels:
        - has-deployment-notes
    - title: Other PRs
      labels:
        - "*"
